# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@useDynLib UmichBiostat815, .registration=TRUE
NULL

#'@title Barzilai Borwein method to determine the step size for gradient descent 
#'@param x  numeric vector for current parameters
#'@param prev_x numeric vector for previous parameters
#'@param grad_x  numeric vector for current gradient
#'@param prev_grad_x vector for previous gradient
#'@param step_size lower bound of the step size
#'@return numeric scalar for step size 
#'@author Jian Kang <jiankang@umich.edu>
#'@examples 
#'set.seed(2023)
#'regdat <- simul_linear_reg(regcoef = c(rep(c(1,-1),length=5),rep(0,length=5)),
#'intercept = 2, 
#'n = 500, R_sq = 0.9)
#'lambda <- 0.04
#'step_size <- 0.001
#'n = length(regdat$y)
#'p = ncol(regdat$X)
#'b <- rnorm(p+1)
#'X1 <- cbind(1,regdat$X)
#'resid <- regdat$y - X1%*%b
#'grad_b <- crossprod(X1,-resid)/n + lambda*b
#'prev_b <- b
#'b <- b - step_size*grad_b
#'resid <- regdat$y - X1%*%b
#'prev_grad_b <- grad_b
#'grad_b <- crossprod(X1,-resid)/n + lambda*b
#'f <- function(x) return(ridge_reg_loss(x[1],x[-1],lambda,regdat$y,regdat$X))
#'prev_step_size <- step_size
#'step_size <-  Barzilai_Borwein_method_cpp(b, prev_b, grad_b, prev_grad_b)
#'print(c(f(b+prev_step_size*prev_grad_b),f(b),f(b-step_size*grad_b)))
#'@export
Barzilai_Borwein_method_cpp <- function(x, prev_x, grad_x, prev_grad_x, step_size_lb = 1e-6) {
    .Call(`_UmichBiostat815_Barzilai_Borwein_method_cpp`, x, prev_x, grad_x, prev_grad_x, step_size_lb)
}

#'@title Backtraking line search in Rcpp
#'@param paras current value of the parameter
#'@param grad_paras current value of the gradient parameter
#'@param obj_fun objective function to be minimized
#'@param dat list object for additional information for the objective function
#'@param a numeric scalar between (0, 0.5)
#'@param b numeric scalar between (0, 1)
#'@return numeric value for the step_size
#'@author Jian Kang <jiankang@umich.edu>
#'@export
backtracking_line_search_cpp <- function(paras, grad_paras, obj_fun, dat, a = 0.25, b = 0.5, max_iter = 1000L) {
    .Call(`_UmichBiostat815_backtracking_line_search_cpp`, paras, grad_paras, obj_fun, dat, a, b, max_iter)
}

#'@title Gradient descent algorithm with different step size methods
#'@param paras numeric vector
#'@param obj_fun objective function to be minimized
#'@param grad_fun gradient function
#'@param dat list object to pass other data to the objective function 
#'and the gradient of the objective functions
#'@param step_size_method indicate the methods to determine the step size
#'@param max_iter positive integer for maximum number of iterations
#'@param step_size numeric scalar for the step size
#'@param tol tolerance for the stopping criterion
#'@author Jian Kang <jiankang@umich.edu>
#'@return a list of objects
#'@examples 
#'regdat <- simul_linear_reg(n = 1000, p = 5, pos_corr = 0.6)
#'regdat$lambda = 0.001
#'res <- gradient_descent_cpp(paras=rep(0,length=ncol(regdat$X)),
#'ridge_reg_loss_cpp,grad_ridge_reg_loss_cpp,regdat)
#'@export
gradient_descent_cpp <- function(paras, obj_fun, grad_fun, dat, step_size_method = as.character( c("fixed","back","BB")), max_iter = 100000L, step_size = 1e-4, tol = 1e-4, verbose = 100L) {
    .Call(`_UmichBiostat815_gradient_descent_cpp`, paras, obj_fun, grad_fun, dat, step_size_method, max_iter, step_size, tol, verbose)
}

#'@title Stochastic Gradient descent algorithm with different step size methods
#'@param paras numeric vector
#'@param obj_fun objective function to be minimized
#'@param grad_fun gradient function
#'@param dat list object to pass other data to the objective function 
#'and the gradient of the objective functions
#'@param step_size_method indicate the methods to determine the step size
#'@param n total numbers of sub functions in the objective function
#'@param max_iter positive integer for maximum number of iterations
#'@param weight number between 0 and 1 to indicate the rate to smooth the gradient over iterations
#'@param step_size numeric scalar for the initial step size
#'@param diminishing_ratio the rate of decreasing the step size
#'@param tol tolerance for the stopping criterion
#'@author Jian Kang <jiankang@umich.edu>
#'@return a list of objects
#'@examples 
#'regdat <- simul_linear_reg(n = 1000, p = 5, pos_corr = 0.6)
#'regdat$lambda = 0.001
#'res <- sgd_cpp(paras=rep(0,length=ncol(regdat$X)),ridge_reg_loss_cpp,
#'grad_ridge_reg_loss_cpp,regdat,
#'step_size_method = "decreasing")
#'
#'@export
sgd_cpp <- function(paras, obj_fun, grad_fun, dat, step_size_method = as.character( c("fixed","decreasing","BB")), n = -1L, max_iter = 10000L, mini_batch_size = 1L, update_freq = 100L, weight = 1.0, step_size = 1e-4, diminishing_ratio = 0.01, r = 0.55, tol = 1e-4, burnin = 5000L, verbose = 1000L) {
    .Call(`_UmichBiostat815_sgd_cpp`, paras, obj_fun, grad_fun, dat, step_size_method, n, max_iter, mini_batch_size, update_freq, weight, step_size, diminishing_ratio, r, tol, burnin, verbose)
}

#'@title Compute loss of the ridge regression in Rcpp
#'@param beta numeric vector for regression coefficients
#'@param dat list object containing covariate matrix, response variable
#'@param idx_R vector of positive integers for sample indices. 
#'@return value of the loss function
#'@author Jian Kang <jiankang@umich.edu>
#'@export
ridge_reg_loss_cpp <- function(beta, dat, idx_R = as.integer( c())) {
    .Call(`_UmichBiostat815_ridge_reg_loss_cpp`, beta, dat, idx_R)
}

#'@title compute the gradient of the ridge regression loss in Rcpp
#'@param beta regression coefficients
#'@param dat list object containing covariate matrix, response variable
#'@param idx_R vector of positive integers for sample indices. 
#'@return a vector of gradient of the loss function
#'@author Jian Kang <jiankang@umich.edu>
#'@export
grad_ridge_reg_loss_cpp <- function(beta, dat, idx_R = as.integer( c())) {
    .Call(`_UmichBiostat815_grad_ridge_reg_loss_cpp`, beta, dat, idx_R)
}

